normal:
  https://yomou.syosetu.com/search.php?word=
option:
  -bookmark:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=favnovelcnt
  -bm:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=favnovelcnt
  -new:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=new
  -n:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=new
  -review:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=reviewcnt
  -r:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=reviewcnt
  -allsynthesis:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=hyoka
  -as:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=hyoka
  -synthesis:
    https://yomou.syosetu.com/search.php?notnizi=1&word=urlorder=hyokacnt
  -s:
    https://yomou.syosetu.com/search.php?notnizi=1&word=urlorder=hyokacnt
  -daily:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=dailypoint
  -dp:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=dailypoint
  -weekly:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=weeklypoint
  -wp:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=weeklypoint
  -monthy:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=monthlypoint
  -mp:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=monthlypoint
  -quarter:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=quarterpoint
  -qp:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=quarterpoint
  -year:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=yearlypoint
  -yp:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=yearlypoint
  -word:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=lengthdesc
  -w:
    https://yomou.syosetu.com/search.php?notnizi=1&word=url&order=lengthdesc
  -help: |
    -bm：ブックマーク登録の多い順
    -n：新着順
    -r：レビューの多い順
    -as：総合評価の高い順
    -s：評価者数の多い順
    -dp：日間ポイントの高い順
    -wp：週間ポイントの高い順
    -mp：月間ポイントの高い順
    -qp：四半期ポイントの高い順
    -yp：年間ポイントの高い順
    -w：文字数の高い順
